[MJAVACC-85] Forked jjdoc-command to generate BNF fails with NoClassDefFoundError: JJDocMain [MJAVACC-86] Forked execution of JTB fails due to incomplete class path